#!/bin/bash
xdotool keydown Alt click 4 keyup Alt

#xdotool sleep 0.100 keydown Alt sleep 0.100 click 4 sleep 0.100 keyup Alt
[Desktop Entry]
Version=1.0
Type=Application
Name=script
Comment=
Exec="/home/scarlet/Documents/Mint\ Configurations/Zoom\ In.sh"
Icon=
Path=
Terminal=true
StartupNotify=false

